apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: brianjcal/myapp
    name: myapp
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always